services:

  backend:
    build: ./backend
    container_name: vegetable-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: "110704"
      DB_NAME: khmer_vegetable_market
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./project
    container_name: vegetable-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: vegetable-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "110704"
      MYSQL_DATABASE: khmer_vegetable_market
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p110704"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
